FF and Rewind added to GPIO_SETTINGS.ini
MiczFlor/RPi-Jukebox-RFID pull request #1291
Opened 2021-02-07 20:33 UTC by Caliandroid

Added two new entries for Fast Forward and Rewind in the gpio_settings.ini  (disabled by default)

2021-02-14 21:10 UTC, s-martin requested changes
I would suggest to use pins not already used in the file, so users using this file directly don't end in a conflict.

2021-02-15 20:19 UTC, Caliandroid commented
@s-martin : Good point! I've changed the pins to unused (7 & 8) + changed the double-usage pin 21 for RFID

2021-02-15 20:22 UTC, Caliandroid commented on components/gpio_control/example_configs/gpio_settings.ini
> +Pin: 7
Changed to unused pin 7

2021-02-15 20:22 UTC, Caliandroid commented on components/gpio_control/example_configs/gpio_settings.ini
> +Pin: 8
Changed to unused pin 8

2021-02-15 20:24 UTC, Caliandroid reviewed
double usasge pin numbers issue resolved

2021-02-15 20:24 UTC, Caliandroid commented on components/gpio_control/example_configs/gpio_settings.ini
> +Pin: 25
changed to resolve double-usage of the same pin as in usage for RFID

2021-02-15 20:25 UTC, s-martin approved these changes

2021-02-15 20:25 UTC, merged