add details about cards for RC522
MiczFlor/RPi-Jukebox-RFID pull request #2372
Opened 2024-05-15 13:07 UTC by s-martin

More details, which cards work for RC522.

See discussion #2340

2024-05-15 18:14 UTC, s-martin commented
This PR changes V3, while the original issue is regarding V2.

2024-05-17 13:40 UTC, AlvinSchiller requested changes

2024-05-17 13:40 UTC, AlvinSchiller commented on documentation/developers/rfid/mfrc522_spi.md
> +Cards or tags must support 13.56 MHz. NTAG product numbers should be S50 or S70.
```suggestion
Cards or tags must support 13.56 MHz. Currently, only cards/tags of the type "NXP Mifare Classic 1k(S50)", "NXP Mifare Classic 4k(S70)" and "NXP Mifare Ultralight (C)" can be used. Type "NXP Mifare NTAG2xx" will not work!
```

2024-05-17 13:41 UTC, AlvinSchiller commented
https://www.nfc-tag-shop.de/info/wissen/nfc-entwicklung/uebersicht-ueber-nfc-chiptypen/ 
Explanation of different types (german)

2024-05-17 17:24 UTC, AlvinSchiller approved these changes

2024-05-17 17:39 UTC, merged