feat: add basic mqtt support
MiczFlor/RPi-Jukebox-RFID pull request #2412
Opened 2024-08-03 22:13 UTC by c0un7-z3r0

This adds initial support and functionality for MQTT. Trying to be downward compatible as much as possible so potential mqtt implementations are not totally broken. Not all legacy features could be ported since the current future3 is not supporting them. Yet.

2024-08-24 08:57 UTC, s-martin requested changes
thanks for your contribution! 

Please add a short doc file in `documentation/builders/components`, which helps users how to use the new MQTT feature.

2024-08-24 08:57 UTC, s-martin commented on src/jukebox/components/mqtt/mqtt_command_alias.py
> +See []
This line could be removed.

2024-11-03 13:56 UTC, pabera reviewed
Sorry, it took me a while to get back to Phoniebox coding. This is a great addition. I have made only a few comments, the quality of code looks alright for now.

How do you use this code? What does your integration look like? Am I correct that this code does not work with Home Automations out of the box yet?

2024-12-09 15:31 UTC, c0un7-z3r0 commented
@s-martin I added a short documentation about the MQTT feature.

@pabera The implementation is working and can be used over MQTT already. Home Assistant is not natively supporting MQTT Media Players so I build in the past a little HACS add on to allow the control of phoniebox via mqtt. https://github.com/c0un7-z3r0/hass-phoniebox

This extension is more or less a mapping of the MQTT events to the internal home assistant media player implementation. But the same can be achieved with the [Universal Media Player](https://www.home-assistant.io/integrations/universal/) from HA just needs manual mapping of events.

Not sure if other Home Automation Systems support MQTT Media Players out of the box.

2024-12-09 15:33 UTC, c0un7-z3r0 commented on src/jukebox/components/mqtt/__init__.py
> +    port = cfg.setndefault("mqtt", "port", value=1883)
good point. I added an enable flag in the jukebox.yaml config of this component.

example config

``` yaml
modules:
    named:
        ...
        mqtt: mqtt
...
mqtt:
    enable: true
    # The client id used in communication with the MQTT broker and identification of the phoniebox
    client_id: phoniebox_dev
    # The username to authenticate against the broker
    username: phoniebox-dev
    # The password to authenticate against the broker
    password: secret-password
    # The host name or IP address of your mqtt broker
    host: 127.0.0.1
    # The port number of the mqtt broker. The default is 1883
    port: 1883
```

2024-12-09 18:04 UTC, s-martin approved these changes

2025-01-09 17:02 UTC, gandy92 commented
Hi, this is exactly what I currently need. However, subscribing to the command topic "phoniebox-dev/cmd/#" (hard-coded btw, not using the base_topic config) did not work out of the box: I only got it working after adding a line ```self._mqtt_client.subscribe("phoniebox-dev/cmd/#", 0);``` after the call to ```self._mqtt_client.message_callback_add()```. 
My pano_mqtt version is 2.1.0

Can you check if you can reproduce this?

2025-01-28 12:55 UTC, c0un7-z3r0 commented
> Hi, this is exactly what I currently need. However, subscribing to the command topic "phoniebox-dev/cmd/#" (hard-coded btw, not using the base_topic config) did not work out of the box: I only got it working after adding a line `self._mqtt_client.subscribe("phoniebox-dev/cmd/#", 0);` after the call to `self._mqtt_client.message_callback_add()`. My pano_mqtt version is 2.1.0
> 
> Can you check if you can reproduce this?

Thanks for commenting @gandy92  🙏.
I fixed the hardcoded command part and for the rest I will check this on my local setup.

2025-02-02 14:13 UTC, s-martin commented
Could be merged, @c0un7-z3r0?
@pabera @AlvinSchiller

2025-02-04 22:21 UTC, pabera approved these changes

2025-02-05 05:32 UTC, merged

2026-05-16 21:15 UTC, Silberwoelfin commented
> > Hi, this is exactly what I currently need. However, subscribing to the command topic "phoniebox-dev/cmd/#" (hard-coded btw, not using the base_topic config) did not work out of the box: I only got it working after adding a line `self._mqtt_client.subscribe("phoniebox-dev/cmd/#", 0);` after the call to `self._mqtt_client.message_callback_add()`. My pano_mqtt version is 2.1.0
> > Can you check if you can reproduce this?
> 
> Thanks for commenting @gandy92 🙏. I fixed the hardcoded command part and for the rest I will check this on my local setup.

I can confirm that the phoniebox is only accepting commands over mqtt after adding the self._mqtt_client.subscribe() line like this:
`def _subscribe(self):`
`        logger.debug("Subscribing to MQTT topics.")`
`        self._mqtt_client.message_callback_add(f'{base_topic}/cmd/#', self._on_cmd)`
`        self._mqtt_client.subscribe(f'{base_topic}/cmd/#',0)`