Replace RPi.GPIO with rpi-lgpio for V2 legacy
MiczFlor/RPi-Jukebox-RFID pull request #2469
Opened 2024-12-22 13:46 UTC by s-martin

Following the discussion in #2313 replacing RPi.GPIO with [rpi-lgpio](https://rpi-lgpio.readthedocs.io/en/latest/index.html)

2024-12-22 13:49 UTC, Groovylein approved these changes

2024-12-22 13:50 UTC, Groovylein commented
I had similar issues and did the same thing. Now everything is working 👍

2024-12-30 00:08 UTC, AlvinSchiller requested changes
This change is not sufficient. If the `pi-rc522` package is installed later on, the dependency for `RPi.GPIO` is resolved and installed. In the end both libs are installed (`rpi-lgpio` and `rpi-gpio`) which breaks the reader.

Possible solution:
On installation of the `pi-rc522` package the option "--no-deps" needs to be added, to not install the `RPi.GPIO` package.

.../components/rfid-reader/RC522/requirements.txt
```
# RC522 related requirements
# You need to install these with `sudo python3 -m pip install --upgrade --force-reinstall --no-deps -q -r requirements.txt`

spidev
pi-rc522==2.3.0
```
.../components/rfid-reader/RC522/setup_rc522.sh#L26
```
sudo python3 -m pip install --upgrade --force-reinstall --no-deps -q -r "${JUKEBOX_HOME_DIR}"/components/rfid-reader/RC522/requirements.txt
```


Downside: if any other package is installed, which has a `RPi.GPIO` dependecy, the reader breaks again. But i did not find any option to block a single package in pip.


Any other/better ideas?

2024-12-30 00:08 UTC, AlvinSchiller commented on scripts/installscripts/install-jukebox.sh
> +    sudo python3 -m pip uninstall rpi-gpio
if the package is already installed, a confirmation of the user is requested. Option `-y` is needed. Also add quite mode `-q`.
```suggestion
    sudo python3 -m pip uninstall -y -q rpi-gpio
```

2024-12-30 00:18 UTC, AlvinSchiller commented
> This change is not sufficient. If the `pi-rc522` package is installed later on, the dependency for `RPi.GPIO` is resolved and installed. In the end both libs are installed (`rpi-lgpio` and `rpi-gpio`) which breaks the reader.
> 
> Possible solution: On installation of the `pi-rc522` package the option "--no-deps" needs to be added, to not install the `RPi.GPIO` package.
> 
> .../components/rfid-reader/RC522/requirements.txt
> 
> ```
> # RC522 related requirements
> # You need to install these with `sudo python3 -m pip install --upgrade --force-reinstall --no-deps -q -r requirements.txt`
> 
> spidev
> pi-rc522==2.3.0
> ```
> 
> .../components/rfid-reader/RC522/setup_rc522.sh#L26
> 
> ```
> sudo python3 -m pip install --upgrade --force-reinstall --no-deps -q -r "${JUKEBOX_HOME_DIR}"/components/rfid-reader/RC522/requirements.txt
> ```
> 
> Downside: if any other package is installed, which has a `RPi.GPIO` dependecy, the reader breaks again. But i did not find any option to block a single package in pip. Also if the `rpi-lgpio` package would not be installed before, the reader is also non-functional (but as it is listed in our main reqiurement, this is negligible).
> 
> Any other/better ideas?

Another option would be to use the [pi-rc522-gpiozero](https://github.com/hoffie/pi-rc522-gpiozero) from @hoffie. But i did not test it yet.

2024-12-31 15:12 UTC, s-martin commented
> This change is not sufficient. If the `pi-rc522` package is installed later on, the dependency for `RPi.GPIO` is resolved and installed. In the end both libs are installed (`rpi-lgpio` and `rpi-gpio`) which breaks the reader.

Good catch!

[…]

> Downside: if any other package is installed, which has a `RPi.GPIO` dependecy, the reader breaks again. But i did not find any option to block a single package in pip. Also if the `rpi-lgpio` package would not be installed before, the reader is also non-functional (but as it is listed in our main reqiurement, this is negligible).
> 
> Any other/better ideas?

For me the downside would be ok as we don’t want to add new functionality to V2 (= no new packages) - nevertheless I’m aware so far we updated many things on V2 although we didn’t want to.

maybe we can add a test to CI, which at least recognizes, if we install RPi.GPIO again.

2025-01-01 13:20 UTC, AlvinSchiller commented
Turns out there are some more problems, regarding compatibility to bullseye. 
The rpi-lgpio lib throws errors as it seems the binary of lgpio is broken fit bullseye (glibc is expected in version 2.33 but bullseye only has 2.31).
It works though if lgpio is build manually.

I also tried to keep RPi.GPIO for bullseye, but that was complicated to handle, especially for automatic tests.

Also the order of de-/installation of the two libs is important. It must be a deinstallation first, otherwise imports are broken
(I tried to play around the" no-deps" option, but this was the showstopper for this solution).


What seems to work now (final tests pending, but ci looks good. Commit with the changes will follow):
- On setup(or update) the old rpi-gpio lib is removed (pip and apt as bullseye has the apt package installed by default and pip can't remove it).
- install rpi-lgpio as replacement
- manually handle libs with dependencies to RPi.GPIO (currently only pi-rc22) with the "no-deps" option.
- for bullseye and below manually build lgpio

2025-01-01 13:40 UTC, AlvinSchiller commented
Also to mention are some incompatibilities of the libs. See [rpi-lgpio differences](https://rpi-lgpio.readthedocs.io/en/latest/differences.html)

- [Pi 1 Models](https://rpi-lgpio.readthedocs.io/en/latest/differences.html#pi-revision) (B, A, A+, B+, and Compute Module 1) are not supported right away, and need a special environment variable to work. I think this is not a big issue but needs to be documented. 

- The [gpio_function](https://rpi-lgpio.readthedocs.io/en/latest/differences.html#alternate-pin-modes) function behave differently but I didn't usage of it in the project. 

- [simultaneous access](https://rpi-lgpio.readthedocs.io/en/latest/differences.html#simultaneous-access) of pins does not work anymore. Should not be a problem for the main functionality but some special use case with hardware might not work. 

- [debounce](https://rpi-lgpio.readthedocs.io/en/latest/differences.html#debounce) behaviour has changed, which might cause some unexpected delay.

2025-01-03 22:33 UTC, s-martin commented on components/rfid-reader/RC522/requirements.txt
> +#pi-rc522 has RPi.GPIO as a dependecy which is broken since kernel 6.6.
```suggestion
#pi-rc522 has RPi.GPIO as a dependency which is broken since kernel 6.6.
```

2025-01-03 22:33 UTC, s-martin commented on scripts/installscripts/install-jukebox.sh
> +    # Remove exluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```suggestion
    # Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```

2025-01-03 22:33 UTC, s-martin commented on CONTRIBUTING.md
> +    > The original `RPi.GPIO` packages is currently not compatible with the 6.6 kernel (since bookworm). Therefore the lib `rpi-lgpio` is used as a replacement, which is api compliant. `RPi.GPIO` mus
```suggestion
    > The original `RPi.GPIO` package is currently not compatible with the 6.6 kernel (since bookworm). Therefore the lib `rpi-lgpio` is used as a replacement, which is api compliant. `RPi.GPIO` **must not** be installed directly or as a dependency as this breaks GPIO functionality (see `requirements-excluded`)!
```

2025-01-03 22:33 UTC, s-martin commented on packages-excluded.txt
> +# Remove exluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```suggestion
# Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```

2025-01-03 22:33 UTC, s-martin commented on requirements-excluded.txt
> +# Remove exluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```suggestion
# Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```

2025-01-03 22:33 UTC, s-martin commented on scripts/installscripts/install-jukebox.sh
> +    # Remove exluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```suggestion
    # Remove excluded libs, if installed - see https://github.com/MiczFlor/RPi-Jukebox-RFID/pull/2469
```

2025-01-03 22:33 UTC, s-martin commented on scripts/installscripts/install-jukebox.sh
> +        mkdir -p tmp && cd tmp && wget -q http://abyz.me.uk/lg/lg.zip && unzip lg.zip > /dev/null && cd lg && make > /dev/null && sudo make install > /dev/null
Do we need to pin a version here?

2025-01-06 21:51 UTC, AlvinSchiller commented on scripts/installscripts/install-jukebox.sh
> +        mkdir -p tmp && cd tmp && wget -q http://abyz.me.uk/lg/lg.zip && unzip lg.zip > /dev/null && cd lg && make > /dev/null && sudo make install > /dev/null
You mean for lgpio? I didn't find a versioned zip file, only the one with latest and greatest, as described in the installation guide.

2025-01-06 21:51 UTC, AlvinSchiller approved these changes

2025-01-06 21:52 UTC, s-martin commented on scripts/installscripts/install-jukebox.sh
> +        mkdir -p tmp && cd tmp && wget -q http://abyz.me.uk/lg/lg.zip && unzip lg.zip > /dev/null && cd lg && make > /dev/null && sudo make install > /dev/null
Ok, then we keep it that way

2025-01-20 07:42 UTC, merged